# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'three-positive-things' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for three-positive-things
  pod 'JTAppleCalendar', '~> 6.0'
  pod 'ChameleonFramework/Swift'
  pod 'DBSphereTagCloudSwift'
  pod 'Firebase'

  target 'three-positive-thingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'three-positive-thingsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
